

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ProvidedService : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProvidedService entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProvidedService()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProvidedService(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProvidedService> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProvidedService.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProvidedService_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProvidedService_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ProvidedService.DetailsClass.GetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ProvidedService.DetailsClass.SetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Count
        {
            get
            {
                return global::LightSwitchApplication.ProvidedService.DetailsClass.GetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Count);
            }
            set
            {
                global::LightSwitchApplication.ProvidedService.DetailsClass.SetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Count, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Count_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Count_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Count_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Price
        {
            get
            {
                return global::LightSwitchApplication.ProvidedService.DetailsClass.GetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Price);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Invoice Invoice
        {
            get
            {
                return global::LightSwitchApplication.ProvidedService.DetailsClass.GetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Invoice);
            }
            set
            {
                global::LightSwitchApplication.ProvidedService.DetailsClass.SetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Invoice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoice_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Service Service
        {
            get
            {
                return global::LightSwitchApplication.ProvidedService.DetailsClass.GetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Service);
            }
            set
            {
                global::LightSwitchApplication.ProvidedService.DetailsClass.SetValue(this, global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Service, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Service_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Service_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Service_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProvidedService,
                global::LightSwitchApplication.ProvidedService.DetailsClass,
                global::LightSwitchApplication.ProvidedService.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>.Entry
                __ProvidedServiceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProvidedService.DetailsClass.__ProvidedService_CreateNew,
                    global::LightSwitchApplication.ProvidedService.DetailsClass.__ProvidedService_Created,
                    global::LightSwitchApplication.ProvidedService.DetailsClass.__ProvidedService_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProvidedService __ProvidedService_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProvidedService> es)
            {
                return new global::LightSwitchApplication.ProvidedService(es);
            }
            private static void __ProvidedService_Created(global::LightSwitchApplication.ProvidedService e)
            {
                e.ProvidedService_Created();
            }
            private static bool __ProvidedService_AllowSaveWithErrors(global::LightSwitchApplication.ProvidedService e)
            {
                bool result = false;
                e.ProvidedService_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int> Count
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Count) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, decimal> Price
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Price) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Invoice> Invoice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Invoice) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Invoice>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Service> Service
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Service) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Service>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int Count { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Invoice { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Service { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProvidedService.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProvidedService.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ProvidedService e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ProvidedService e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ProvidedService e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Entry
                    Count = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Entry(
                        "Count",
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Count_Stub,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Count_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Count_Validate,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Count_GetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Count_SetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Count_OnValueChanged);
                private static void _Count_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProvidedService.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProvidedService.DetailsClass d, object sf)
                {
                    c(d, ref d._Count, sf);
                }
                private static bool _Count_ComputeIsReadOnly(global::LightSwitchApplication.ProvidedService e)
                {
                    bool result = false;
                    e.Count_IsReadOnly(ref result);
                    return result;
                }
                private static void _Count_Validate(global::LightSwitchApplication.ProvidedService e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Count_Validate(r);
                }
                private static int _Count_GetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    return d.ImplementationEntity.Count;
                }
                private static void _Count_SetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Count = v;
                }
                private static void _Count_OnValueChanged(global::LightSwitchApplication.ProvidedService e)
                {
                    e.Count_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, decimal>.Entry
                    Price = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, decimal>.Entry(
                        "Price",
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Price_Stub,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Price_Validate,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Price_ComputeValue);
                private static void _Price_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProvidedService.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ProvidedService.DetailsClass d, object sf)
                {
                    c(d, ref d._Price, sf);
                }
                private static void _Price_Validate(global::LightSwitchApplication.ProvidedService e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Price_Validate(r);
                }
                private static decimal _Price_ComputeValue(global::LightSwitchApplication.ProvidedService e)
                {
                    decimal value = default(decimal);
                    e.Price_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Invoice>.Entry
                    Invoice = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Invoice>.Entry(
                        "Invoice",
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_Stub,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_Validate,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_GetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_SetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_Refresh,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Invoice_OnValueChanged);
                private static void _Invoice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProvidedService.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Invoice>.Data> c, global::LightSwitchApplication.ProvidedService.DetailsClass d, object sf)
                {
                    c(d, ref d._Invoice, sf);
                }
                private static bool _Invoice_ComputeIsReadOnly(global::LightSwitchApplication.ProvidedService e)
                {
                    bool result = false;
                    e.Invoice_IsReadOnly(ref result);
                    return result;
                }
                private static void _Invoice_Validate(global::LightSwitchApplication.ProvidedService e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Invoice_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Invoice_GetCoreImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    return d.ImplementationEntity.Invoice;
                }
                private static global::LightSwitchApplication.Invoice _Invoice_GetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Invoice, ref d._Invoice);
                }
                private static void _Invoice_SetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d, global::LightSwitchApplication.Invoice v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Invoice, ref d._Invoice, (i, ev) => i.Invoice = ev, v);
                }
                private static void _Invoice_Refresh(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Invoice, ref d._Invoice);
                }
                private static void _Invoice_OnValueChanged(global::LightSwitchApplication.ProvidedService e)
                {
                    e.Invoice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Service>.Entry
                    Service = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Service>.Entry(
                        "Service",
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_Stub,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_Validate,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_GetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_SetImplementationValue,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_Refresh,
                        global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties._Service_OnValueChanged);
                private static void _Service_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProvidedService.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Service>.Data> c, global::LightSwitchApplication.ProvidedService.DetailsClass d, object sf)
                {
                    c(d, ref d._Service, sf);
                }
                private static bool _Service_ComputeIsReadOnly(global::LightSwitchApplication.ProvidedService e)
                {
                    bool result = false;
                    e.Service_IsReadOnly(ref result);
                    return result;
                }
                private static void _Service_Validate(global::LightSwitchApplication.ProvidedService e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Service_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Service_GetCoreImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    return d.ImplementationEntity.Service;
                }
                private static global::LightSwitchApplication.Service _Service_GetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Service, ref d._Service);
                }
                private static void _Service_SetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass d, global::LightSwitchApplication.Service v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Service, ref d._Service, (i, ev) => i.Service = ev, v);
                }
                private static void _Service_Refresh(global::LightSwitchApplication.ProvidedService.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProvidedService.DetailsClass.PropertySetProperties.Service, ref d._Service);
                }
                private static void _Service_OnValueChanged(global::LightSwitchApplication.ProvidedService e)
                {
                    e.Service_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, int>.Data _Count;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, decimal>.Data _Price;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Invoice>.Data _Invoice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass, global::LightSwitchApplication.Service>.Data _Service;
            
        }
    
        #endregion
    }
    
    #endregion
}
