

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Service : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Service entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Service()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Service(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Service> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Service.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Service_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Service_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Service.DetailsClass.SetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Code
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Code);
            }
            set
            {
                global::LightSwitchApplication.Service.DetailsClass.SetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Code, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Service.DetailsClass.SetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Price
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Price);
            }
            set
            {
                global::LightSwitchApplication.Service.DetailsClass.SetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Price, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Service.DetailsClass.SetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DisplayName
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.DisplayName);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayName_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProvidedService> ProvidedServices
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetValue(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.ProvidedServices);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProvidedService> ProvidedServicesQuery
        {
            get
            {
                return global::LightSwitchApplication.Service.DetailsClass.GetQuery(this, global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.ProvidedServices);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Service,
                global::LightSwitchApplication.Service.DetailsClass,
                global::LightSwitchApplication.Service.DetailsClass.IImplementation,
                global::LightSwitchApplication.Service.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>.Entry
                __ServiceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>.Entry(
                    global::LightSwitchApplication.Service.DetailsClass.__Service_CreateNew,
                    global::LightSwitchApplication.Service.DetailsClass.__Service_Created,
                    global::LightSwitchApplication.Service.DetailsClass.__Service_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Service __Service_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Service> es)
            {
                return new global::LightSwitchApplication.Service(es);
            }
            private static void __Service_Created(global::LightSwitchApplication.Service e)
            {
                e.Service_Created();
            }
            private static bool __Service_AllowSaveWithErrors(global::LightSwitchApplication.Service e)
            {
                bool result = false;
                e.Service_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Service.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int> Code
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Code) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, decimal> Price
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Price) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string> DisplayName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.DisplayName) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, global::LightSwitchApplication.ProvidedService> ProvidedServices
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.ProvidedServices) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, global::LightSwitchApplication.ProvidedService>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int Code { get; set; }
                new string Name { get; set; }
                new decimal Price { get; set; }
                new string Description { get; set; }
                new global::System.Collections.IEnumerable ProvidedServices { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Service e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Service e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Service e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Entry
                    Code = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Entry(
                        "Code",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Code_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Code_ComputeIsReadOnly,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Code_Validate,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Code_GetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Code_SetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Code_OnValueChanged);
                private static void _Code_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._Code, sf);
                }
                private static bool _Code_ComputeIsReadOnly(global::LightSwitchApplication.Service e)
                {
                    bool result = false;
                    e.Code_IsReadOnly(ref result);
                    return result;
                }
                private static void _Code_Validate(global::LightSwitchApplication.Service e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Code_Validate(r);
                }
                private static int _Code_GetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.ImplementationEntity.Code;
                }
                private static void _Code_SetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Code = v;
                }
                private static void _Code_OnValueChanged(global::LightSwitchApplication.Service e)
                {
                    e.Code_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Service e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Service e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Service e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, decimal>.Entry
                    Price = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, decimal>.Entry(
                        "Price",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Price_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Price_ComputeIsReadOnly,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Price_Validate,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Price_GetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Price_SetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Price_OnValueChanged);
                private static void _Price_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._Price, sf);
                }
                private static bool _Price_ComputeIsReadOnly(global::LightSwitchApplication.Service e)
                {
                    bool result = false;
                    e.Price_IsReadOnly(ref result);
                    return result;
                }
                private static void _Price_Validate(global::LightSwitchApplication.Service e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Price_Validate(r);
                }
                private static decimal _Price_GetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.ImplementationEntity.Price;
                }
                private static void _Price_SetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Price = v;
                }
                private static void _Price_OnValueChanged(global::LightSwitchApplication.Service e)
                {
                    e.Price_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Service e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Service e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Service.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Service e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Entry
                    DisplayName = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Entry(
                        "DisplayName",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._DisplayName_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._DisplayName_Validate,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._DisplayName_ComputeValue);
                private static void _DisplayName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._DisplayName, sf);
                }
                private static void _DisplayName_Validate(global::LightSwitchApplication.Service e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DisplayName_Validate(r);
                }
                private static string _DisplayName_ComputeValue(global::LightSwitchApplication.Service e)
                {
                    string value = default(string);
                    e.DisplayName_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, global::LightSwitchApplication.ProvidedService>.Entry
                    ProvidedServices = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, global::LightSwitchApplication.ProvidedService>.Entry(
                        "ProvidedServices",
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._ProvidedServices_Stub,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._ProvidedServices_GetReferencedEntities,
                        global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties._ProvidedServices_GetEntityCollection);
                private static void _ProvidedServices_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Service.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, global::LightSwitchApplication.ProvidedService>.Data> c, global::LightSwitchApplication.Service.DetailsClass d, object sf)
                {
                    c(d, ref d._ProvidedServices, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProvidedService> _ProvidedServices_GetReferencedEntities(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProvidedService, global::LightSwitchApplication.ProvidedService.DetailsClass>(global::LightSwitchApplication.Service.DetailsClass.PropertySetProperties.ProvidedServices, ref d._ProvidedServices);
                }
                private static global::System.Collections.IEnumerable _ProvidedServices_GetEntityCollection(global::LightSwitchApplication.Service.DetailsClass d)
                {
                    return d.ImplementationEntity.ProvidedServices;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, int>.Data _Code;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, decimal>.Data _Price;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, string>.Data _DisplayName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Service, global::LightSwitchApplication.Service.DetailsClass, global::LightSwitchApplication.ProvidedService>.Data _ProvidedServices;
            
        }
    
        #endregion
    }
    
    #endregion
}
